### ISSUE TITLE
Shouldn't min. python supported be 3.8?

### ISSUE THREAD

**Issue by whillas** [danielgtaylor/python-betterproto#120]
I just tried to install it with Python 3.7 and got:

> attributeError: type object 'Callable' has no attribute '_abc_registry'

A quick search of this repo for Callable and your using this in a few places but [according to the docs](https://docs.python.org/3/library/typing.html#typing.Callable) its "New in version 3.8"?

Is this correct?

**Comment by nat-n** [comment]
The tests pass in CI for 3.6 & 3.7, and I’ve been using betterproto for projects on 3.6.8, so I suspect that’s not the issue.

I’m not sure what that error is about and couldn’t guess without more context, but typing.Callable is definitely available in 3.6.

https://docs.python.org/3.6/library/typing.html#typing.Callable

I’ll close this issue for now.

**Comment by fy0** [comment]
same error:

```
>pip3 install "betterproto[compiler]"
Collecting betterproto[compiler]
  Downloading betterproto-1.2.5.tar.gz (26 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\ProgramData\Miniconda3\python.exe' 'D:\ProgramData\Miniconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\user\AppData\Local\Temp\pip-build-env-n5f8ay1s\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "D:\ProgramData\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "D:\ProgramData\Miniconda3\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "D:\ProgramData\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\commands\install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\cli\req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\index\package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_vendor\requests\__init__.py", line 114, in <module>
      from . import utils
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
      from . import certs
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_vendor\requests\certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
      from .core import contents, where
    File "D:\ProgramData\Miniconda3\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
      from importlib.resources import read_text
    File "D:\ProgramData\Miniconda3\lib\importlib\resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "D:\ProgramData\Miniconda3\lib\site-packages\typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "D:\ProgramData\Miniconda3\lib\site-packages\typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\ProgramData\Miniconda3\python.exe' 'D:\ProgramData\Miniconda3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\user\AppData\Local\Temp\pip-build-env-n5f8ay1s\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

C:\Users\user>
```

python:
```
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)]
```

**Comment by Gobot1234** [comment]
Run `pip uninstall typing` to fix this for future reference.
