### ISSUE TITLE
Weakness in casing.sanitize_name()

### ISSUE THREAD

**Issue by lelit** [danielgtaylor/python-betterproto#210]
I think that `casing.sanitize_name()` should also consider (some) `__builtins__` names, at least those actually used in the generated source.

Consider the following definition:
```
syntax = "proto3";

package test;

message Test {
  string str = 1;
}
```
where the attribute is named `str`.

Generation succeds:
```
$ protoc -I . --python_betterproto_out=out test.proto
Writing __init__.py
Writing test.py
```

But import fails:
```
$ python -c 'import out.test'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/foo/out/test.py", line 10, in <module>
    class Test(betterproto.Message):
  File "/usr/lib/python3.9/dataclasses.py", line 1021, in dataclass
    return wrap(cls)
  File "/usr/lib/python3.9/dataclasses.py", line 1013, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib/python3.9/dataclasses.py", line 993, in _process_class
    str(inspect.signature(cls)).replace(' -> None', ''))
  File "/usr/lib/python3.9/inspect.py", line 3087, in __str__
    formatted = str(param)
  File "/usr/lib/python3.9/inspect.py", line 2606, in __str__
    formatannotation(self._annotation))
  File "/usr/lib/python3.9/inspect.py", line 1240, in formatannotation
    return repr(annotation)
  File "/usr/lib/python3.9/dataclasses.py", line 260, in __repr__
    return ('Field('
  File "/usr/lib/python3.9/dataclasses.py", line 260, in __repr__
    return ('Field('
  File "/usr/lib/python3.9/dataclasses.py", line 260, in __repr__
    return ('Field('
  [Previous line repeated 487 more times]
RecursionError: maximum recursion depth exceeded
```

**Comment by Gobot1234** [comment]
What version of betterproto are you on I'm pretty sure this is fixed by 2.0.0b2

**Comment by lelit** [comment]
That was with the current _stable_ version, 1.2.5.
But I get the same with 2.0.0b2:
```
$ pip install betterproto==2.0.0b2
....

$ mkdir out2

$ protoc -I . --python_betterproto_out=out2 test.proto
Writing __init__.py
Writing test/__init__.py

$ python -c 'import out2.test'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/foo/out2/test/__init__.py", line 10, in <module>
    class Test(betterproto.Message):
  File "/usr/lib/python3.9/dataclasses.py", line 1013, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/usr/lib/python3.9/dataclasses.py", line 993, in _process_class
    str(inspect.signature(cls)).replace(' -> None', ''))
  File "/usr/lib/python3.9/inspect.py", line 3087, in __str__
    formatted = str(param)
  File "/usr/lib/python3.9/inspect.py", line 2606, in __str__
    formatannotation(self._annotation))
  File "/usr/lib/python3.9/inspect.py", line 1240, in formatannotation
    return repr(annotation)
  File "/usr/lib/python3.9/dataclasses.py", line 260, in __repr__
    return ('Field('
  File "/usr/lib/python3.9/dataclasses.py", line 260, in __repr__
    return ('Field('
  File "/usr/lib/python3.9/dataclasses.py", line 260, in __repr__
    return ('Field('
  [Previous line repeated 488 more times]
RecursionError: maximum recursion depth exceeded while getting the repr of an object

$ pip freeze | grep betterproto
betterproto==2.0.0b2
```

**Comment by Gobot1234** [comment]
What version of python are you on?

**Comment by lelit** [comment]
Python 3.9.1, on a Debian `sid`.

**Comment by Gobot1234** [comment]
#193 is sort of a a PR for this, although it will need to made for all builtin types not just bytes.

**Comment by lelit** [comment]
Right, I missed it, sorry. 

Indeed, as exhibited above it's not a _compilation_ problem but rather a _runtime_ error. And yes, as said `sanitize_name()` should probably consider any `__builtins__` name used in the generated code.

**Comment by giantryansaul** [comment]
I am also experiencing this issue using 2.0.0b2 and Python 3.9.2 and 3.8.8 on runtime (tested both interpreters). We have this for one of our messages;

```
message VectorBuffer {
    bytes bytes = 1; // The bytes of your buffer
    ...
}
```

**Comment by Gobot1234** [comment]
This seems like an upstream issue with dataclasses maybe open a bpo and see if it gets fixed?
