### ISSUE TITLE
Betterproto fails to compile empty service without any comments.

### ISSUE THREAD

**Issue by qria** [danielgtaylor/python-betterproto#220]
Betterproto fails to compile when a service is empty without any comments.

example.proto: 
```
syntax = "proto3";

package hello;

service HelloService {}
```

Output of command `python -m grpc_tools.protoc -I . --python_betterproto_out=. example.proto`

```

Traceback (most recent call last):
  File "/Users/qria/.virtualenvs/inference/bin/protoc-gen-python_betterproto", line 8, in <module>
    sys.exit(main())
  File "/Users/qria/.virtualenvs/inference/lib/python3.8/site-packages/betterproto/plugin/main.py", line 28, in main
    generate_code(request, response)
  File "/Users/qria/.virtualenvs/inference/lib/python3.8/site-packages/betterproto/plugin/parser.py", line 123, in generate_code
    f.content = outputfile_compiler(output_file=output_package)
  File "/Users/qria/.virtualenvs/inference/lib/python3.8/site-packages/betterproto/plugin/compiler.py", line 34, in outputfile_compiler
    return black.format_str(
  File "/Users/qria/.virtualenvs/inference/lib/python3.8/site-packages/black.py", line 725, in format_str
    src_node = lib2to3_parse(src_contents.lstrip(), mode.target_versions)
  File "/Users/qria/.virtualenvs/inference/lib/python3.8/site-packages/black.py", line 836, in lib2to3_parse
    raise exc from None
black.InvalidInput: Cannot parse: 14:0: class HelloServiceBase(ServiceBase):
--python_betterproto_out: protoc-gen-python_betterproto: Plugin failed with status code 1.
```

This is because without comments, betterproto generates code like this:

```
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: example.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import Dict

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase
import grpclib


class HelloServiceStub(betterproto.ServiceStub):

class HelloServiceBase(ServiceBase):



    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
        }

```

...which is invalid.

Currently using version 2.0.0b3.

We're probably just going to add comments to it but seems like it's a bug worth mentioning.

**Comment by nat-n** [comment]
I believe this issue should be resolved now in 2.0.0b3. Please comment back here if that's not the case.
