### ISSUE TITLE
Unusable docs in section "Async gRPC Support server-facing"

### ISSUE THREAD

**Issue by tillakhanov** [danielgtaylor/python-betterproto#248]
Unusable docs in section "Async gRPC Support server-facing"

```
Traceback (most recent call last):
  File "/Users/bekhzod/Projects/betterproto-test/.venv/lib/python3.9/site-packages/grpclib/server.py", line 440, in request_handler
    await method_func(stream)
  File "/Users/bekhzod/Projects/betterproto-test/echo/__init__.py", line 72, in __rpc_echo
    await stream.send_message(response)
  File "/Users/bekhzod/Projects/betterproto-test/.venv/lib/python3.9/site-packages/grpclib/server.py", line 195, in send_message
    await send_message(self._stream, self._codec, message, self._send_type)
  File "/Users/bekhzod/Projects/betterproto-test/.venv/lib/python3.9/site-packages/grpclib/stream.py", line 44, in send_message
    reply_bin = codec.encode(message, message_type)
  File "/Users/bekhzod/Projects/betterproto-test/.venv/lib/python3.9/site-packages/grpclib/encoding/proto.py", line 45, in encode
    raise TypeError('Message must be of type {!r}, not {!r}'
TypeError: Message must be of type <class 'echo.EchoResponse'>, not <class 'str'>
```

**Comment by tillakhanov** [comment]
#249
