### ISSUE TITLE
Non-consecutive enum values break serialization

### ISSUE THREAD

**Issue by stopmachine** [danielgtaylor/python-betterproto#320]
Consider this definition:
```Protobuf
enum TestEnum {
    __UNKNOWN   = 0;
    A_VAL       = 1;
    B_VAL       = 42;
}

message TestMsg {
    TestEnum enumVal = 1;
}
```

Trying to serialize to json raises an exception:

```python
>>> from testproto import TestEnum, TestMsg

>>> tm = TestMsg(TestEnum.B_VAL)
>>> tm.to_json()

Traceback (most recent call last):
  File "./.venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-3c5619db1584>", line 1, in <module>
    tm.to_json()
  File "./.venv/lib/python3.8/site-packages/betterproto/__init__.py", line 914, in to_json
    return json.dumps(self.to_dict(), indent=indent)
  File "./.venv/lib/python3.8/site-packages/betterproto/__init__.py", line 846, in to_dict
    output[cased_name] = enum_values[v].name
IndexError: list index out of range
```

**Comment by stopmachine** [comment]
I was using 1.2.5. I didn't notice there's a beta release, indeed it's solved in 2.0.0b4.
