### ISSUE TITLE
__bytes__() throws "ufunc 'bitwise_and' not supported for the input types"

### ISSUE THREAD

**Issue by flexflower** [danielgtaylor/python-betterproto#374]
```py
# export.py
from protobuf import simdata
e_state = simdata.StateSimulationEnvironment()
e_state.clock = self.sim.env.clock

cells = []

for cell in self.sim.env.cells:
    cells.append(simdata.Cell(age=cell.age,
    pos_x=cell.pos[0],
    pos_y=cell.pos[1]))
        
e_state.cells = cells
e_state.newborns = newborns
        
bytes(data)
```
```proto
// simdata.proto
message State {
    message Simulation {
        message Environment {
            int64 clock = 1;
            
            repeated Cell cells = 2;
        }
    }
}

message Cell {
    repeated int64 age = 1;
    repeated int64 pos_x = 2;
    repeated int64 pos_y = 3;
}
```
Throws:
`TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''`

<details>
    <summary>(Full traceback)</summary> 

  ```
Traceback (most recent call last):
File "main.py", line 24, in <module>
    main()
File "main.py", line 21, in main
    exp.state()
File "/home/kelyan/Documents/Acean/plugins/acean/export.py", line 41, in state
    self.export(e_state, 'STATE')
File "/home/kelyan/Documents/Acean/plugins/acean/export.py", line 46, in export
    out = bytes(data)
File "/home/kelyan/.local/lib/python3.8/site-packages/betterproto/__init__.py", line 614, in __bytes__
    output += _serialize_single(
File "/home/kelyan/.local/lib/python3.8/site-packages/betterproto/__init__.py", line 360, in _serialize_single
    value = _preprocess_single(proto_type, wraps, value)
File "/home/kelyan/.local/lib/python3.8/site-packages/betterproto/__init__.py", line 346, in _preprocess_single
    return bytes(value)
File "/home/kelyan/.local/lib/python3.8/site-packages/betterproto/__init__.py", line 624, in __bytes__
    output += _serialize_single(
File "/home/kelyan/.local/lib/python3.8/site-packages/betterproto/__init__.py", line 360, in _serialize_single
    value = _preprocess_single(proto_type, wraps, value)
File "/home/kelyan/.local/lib/python3.8/site-packages/betterproto/__init__.py", line 317, in _preprocess_single
    return encode_varint(value)
File "/home/kelyan/.local/lib/python3.8/site-packages/betterproto/__init__.py", line 298, in encode_varint
    bits = value & 0x7F
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
  ```

</details>

It seems to be working with the following:

```proto
// simdata.proto
message Init {
    message Simulation {
        message Environment {
            int64 grid_size = 1;
            int64 n_cells = 2;
        }
    }
}
```

From my research, it seems like `cells`, more generally `repeated` fields, are the problem. Am I misusing them? `e_state.cells.extend()` doesn't work either (as seen [here](https://stackoverflow.com/a/23726417) for the original protobuf module)

**Comment by flexflower** [comment]
It does seem like you're right, I didn't take that option into consideration. Thank you.
