### ISSUE TITLE
Parsing map message: TypeError: cannot convert 'TestInt' object to bytes

### ISSUE THREAD

**Issue by bw7715** [danielgtaylor/python-betterproto#385]
When I try parse proto message with `bytes()` and `.parse()` I get an error:
```bash
E:\Work\Venvs\python_projects\Scripts\python.exe "E:/Projects/python_projects/communication/string_msg_problem.py"
TestMap(map={'number': TestInt(value=5), 'text': TestString(text='test1', values=['test1', 'test2'])})
Traceback (most recent call last):
  File "E:\Projects\python_projects\communication\string_msg_problem.py", line 26, in <module>
    serialized = bytes(msg)
  File "E:\Work\Venvs\python_projects\lib\site-packages\betterproto\__init__.py", line 801, in __bytes__
    sv = _serialize_single(2, meta.map_types[1], v)
  File "E:\Work\Venvs\python_projects\lib\site-packages\betterproto\__init__.py", line 396, in _serialize_single
    value = _preprocess_single(proto_type, wraps, value)
  File "E:\Work\Venvs\python_projects\lib\site-packages\betterproto\__init__.py", line 382, in _preprocess_single
    return bytes(value)
TypeError: cannot convert 'TestInt' object to bytes

Process finished with exit code 1

```

Code to reproduce:
proto:
```protobuf
syntax = "proto3";

package string_problem;

message TestString
{
  string text = 1;
  repeated string values = 2;
}

message TestInt
{
  int32 value = 1;
}

message TestValue
{
  oneof value_oneof {
    TestInt value_int = 1;
    TestString value_string = 2;
  }
}

message TestMap
{
  map<string, TestValue> map = 1;
}
```

python script:
```python
from dataclasses import dataclass, field
import typing as T
import string_problem as sp


@dataclass
class TestInt:
    value: int


@dataclass
class TestString:
    text: str
    values: T.Collection[str] = field(default_factory=list)


d = {'number': TestInt(value=5), 'text': TestString(text='test1', values=['test1', 'test2'])}

msg = sp.TestMap()

# msg.map = d
msg.map.update(d)

print(msg)

serialized = bytes(msg)  # TypeError: cannot convert 'TestInt' object to bytes
print(serialized)

another = sp.TestMap().parse(serialized)
print(another)
```

Tested on:
Python 3.9 and 3.10
betterproto: 2.0.0b4 and 1.2.5

**Comment by Gobot1234** [comment]
You aren't using the generated the code here. See https://github.com/danielgtaylor/python-betterproto#compiling-proto-files for more info
