### ISSUE TITLE
"IndexError: index out of range" when parse map message with int value and oneof

### ISSUE THREAD

**Issue by bw7715** [danielgtaylor/python-betterproto#386]
When try parse serialized message with map, oneof and int value I get an error:
```bash
msg=TestMap(map={'number': TestValue(value_int=5)})
type=<class 'dict'>
serialized=b'\n\x11\n\x06number\x12\x07\n\x05\x00\x00\x00\x00\x00'

Traceback (most recent call last):
  File "E:\Work\project\proto_with_map.py", line 16, in <module>
    another = TestMap().parse(bytes(serialized))
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 986, in parse
    value = self._postprocess_single(
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 929, in _postprocess_single
    value = self._betterproto.cls_by_field[field_name]().parse(value)
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 986, in parse
    value = self._postprocess_single(
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 926, in _postprocess_single
    value = cls().parse(value)
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 986, in parse
    value = self._postprocess_single(
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 926, in _postprocess_single
    value = cls().parse(value)
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 958, in parse
    for parsed in parse_fields(data):
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 499, in parse_fields
    decoded, i = decode_varint(value, i)
  File "E:\Work\Venvs\betterproto\bp_beta_venv\lib\site-packages\betterproto\__init__.py", line 471, in decode_varint
    b = buffer[pos]
IndexError: index out of range

Process finished with exit code 1
```

Code to reproduce:
Proto:
```protobuf
syntax = "proto3";

package test_map;

message TestString
{
  string text = 1;
  repeated string values = 2;
}

message TestInt
{
  uint32 value = 1;
}

message TestValue
{
  oneof value_oneof {
    TestInt value_int = 1;
    TestString value_string = 2;
  }
}

message TestMap
{
  map<string, TestValue> map = 1;
}

```

Python script:
```python
from lib.test_map import TestMap, TestValue, TestInt, TestString

dict_int = {'number': TestValue(value_int=5)}

msg = TestMap()
msg.map = dict_int
# msg.map.update(dict_int)

print(f"msg={msg}")
print(f"type={type(msg.map)}")

serialized = bytes(msg)
print(f"serialized={serialized}")

another = TestMap().parse(bytes(serialized))  # IndexError: index out of range
print(f"another={another}")
```

Tested on Windows 10
Python 3.10
betterproto 2.0.0b4 and 1.2.5

**Comment by bw7715** [comment]
BetterProto beta pip list:
```bash
PS E:\Work\Venvs\betterproto\bp_beta_venv\Scripts> .\python.exe -m pip list
Package         Version
--------------- --------
betterproto     2.0.0b4
black           22.3.0
click           8.1.3
colorama        0.4.4
grpcio          1.44.0
grpcio-tools    1.44.0
grpclib         0.4.3rc2
h2              4.1.0
hpack           4.0.0
hyperframe      6.0.1
Jinja2          2.11.3
MarkupSafe      2.0.1
multidict       6.0.2
mypy-extensions 0.4.3
pathspec        0.9.0
pip             22.1
platformdirs    2.5.2
protobuf        3.20.1
python-dateutil 2.8.2
setuptools      62.2.0
six             1.16.0
stringcase      1.2.0
tomli           2.0.1
wheel           0.37.1
```

**Comment by bw7715** [comment]
Stable pip list:
```bash
PS E:\Work\Venvs\betterproto\bp_stable_venv\Scripts> .\python.exe -m pip list
Package         Version
--------------- -------
betterproto     1.2.5
black           22.3.0
click           8.1.3
colorama        0.4.4
grpcio          1.46.1
grpcio-tools    1.46.1
grpclib         0.4.2
h2              4.1.0
hpack           4.0.0
hyperframe      6.0.1
Jinja2          3.1.2
MarkupSafe      2.1.1
multidict       6.0.2
mypy-extensions 0.4.3
pathspec        0.9.0
pip             22.1
platformdirs    2.5.2
protobuf        3.20.1
setuptools      62.2.0
six             1.16.0
stringcase      1.2.0
tomli           2.0.1
wheel           0.37.1
```

**Comment by bw7715** [comment]
To fix this, the variable **dict_int** should look like this: ```dict_int = {'number': TestValue(value_int=TestInt(value=5))}```

Now the output:

```bash
msg=TestMap(map={'number': TestValue(value_int=TestInt(value=5))})
type=<class 'dict'>
serialized=b'\n\x0e\n\x06number\x12\x04\n\x02\x08\x05'
another=TestMap(map={'number': TestValue(value_int=TestInt(value=5))})
```

Works with both stable and beta version of betterproto.
