### ISSUE TITLE
Instead of failing on bidirectional stream generate stubbed endpoint

### ISSUE THREAD

**Issue by parkwherever** [danielgtaylor/python-betterproto#389]
Usage: I am trying to switch to betterproto using [buf.build](https://buf.build/judahrand/plugins/python-betterproto)

Error:
```
buf generate
Failure: plugin "buf.build/judahrand/plugins/python-betterproto:v1.2.5-1" exited with non-zero status 1: Traceback (most recent call last):
  File "/usr/local/bin/protoc-gen-python_betterproto", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/betterproto/plugin.py", line 464, in main
    generate_code(request, response)
  File "/usr/local/lib/python3.7/site-packages/betterproto/plugin.py", line 368, in generate_code
    raise NotImplementedError("Client streaming not yet supported")
NotImplementedError: Client streaming not yet supported
```

**Comment by Gobot1234** [comment]
Client streaming is supported on v2.0.0, to install run `pip install -U betterproto --pre`
