### ISSUE TITLE
Cannot parse binary from Pydantic classes

### ISSUE THREAD

**Issue by bourbonut** [danielgtaylor/python-betterproto#586]
### Summary

Cannot parse binary from Pydantic classes

## Requirements
Python version : 3.10.14
```
betterproto==2.0.0b6
pydantic==1.10.17
grpcio
grpcio-tools
```

## Code
```protobuf
// protobuf/system.proto
syntax = "proto3";

package system;

message Item {
  string id = 1;
}
```

```python
# main.py
from protobuf.system import Item

item = Item(id="superid")
binary = bytes(item)
print(Item.FromString(binary))
```

## Compilation
```
python -m grpc_tools.protoc --python_betterproto_opt=pydantic_dataclasses --proto_path=protobuf --python_betterproto_out=protobuf system.proto
```

## Execution
```
python main.py
```

### Expected Results

Without Pydantic :
```
python -m grpc_tools.protoc --proto_path=protobuf --python_betterproto_out=protobuf system.proto
python main.py
```
Output:
```
Item(id='superid')
```

### Actual Results

```
Traceback (most recent call last):
  File "/tmp/pydantic_betterproto/main.py", line 5, in <module>
    print(Item.FromString(binary))
  File "/tmp/.venv/lib/python3.10/site-packages/betterproto/__init__.py", line 1052, in FromString
    return cls().parse(data)
  File "pydantic/dataclasses.py", line 293, in pydantic.dataclasses._add_pydantic_validation_attributes.handle_extra_init
    self.repr = repr
  File "<string>", line 4, in __init__
  File "pydantic/dataclasses.py", line 315, in pydantic.dataclasses._add_pydantic_validation_attributes.new_post_init
    f'_field_type={self._field_type}'
  File "pydantic/dataclasses.py", line 447, in pydantic.dataclasses._dataclass_validate_values
    
pydantic.error_wrappers.ValidationError: 1 validation error for Item
id
  str type expected (type=type_error.str)
```

### System Information

`pip list` : 
```
Package           Version
----------------- -----------
betterproto       2.0.0b6
black             24.4.2
click             8.1.7
grpcio            1.64.1
grpcio-tools      1.64.1
grpclib           0.4.7
h2                4.1.0
hpack             4.0.0
hyperframe        6.0.1
isort             5.13.2
Jinja2            3.1.4
MarkupSafe        2.1.5
multidict         6.0.5
mypy-extensions   1.0.0
packaging         24.1
pathspec          0.12.1
pip               23.0.1
platformdirs      4.2.2
protobuf          5.27.2
pydantic          1.10.17
python-dateutil   2.9.0.post0
setuptools        65.5.0
six               1.16.0
tomli             2.0.1
typing_extensions 4.12.2
```

`python --version` : Python 3.10.14

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have verified this issue occurs on the latest prelease of betterproto which can be installed using `pip install -U --pre betterproto`, if possible.

**Comment by AdrienVannson** [comment]
Hello,

I had the same error: I think the problem comes from `cls()` in ` return cls().parse(data)`. It tries to create an empty instance of the class, which pydantic refuses.

Updating to the last version of pydantic seems to solve the problem for me.

**Comment by Gobot1234** [comment]
This should be fixed when b7 comes out

**Comment by Gobot1234** [comment]
b7 has just been released, install it with `pip install betterproto[compiler] --pre`
